#Тэг перед сообщением
plugin_tag: "[&cЧАТ&f]"

#Предупреждение о мате
warn_msg: "&aСообщение содержит мат"

#Кол-во матных слов до кика
before_kick: 3

#Сообщение при кике игрока с сервера
kick_msg: "Вы были отключены от сервера за использование мата"

#Количество матов перед мутов
before_mute: 5

#Сообщение о муте игрока и на сколько он был замучен
mute_msg: "Вы были замучены на %duration% минут"

#Время мута в минутах
mute_duration: 10

#Звук предупреждения
warn_sound: BLOCK_ANVIL_LAND

#Вести ли логи
write_log: true

#Уведомление адмену о попытке написать мат в чат
notify: true